#!/bin/bash

USER_PATH="/home/$USER/code/i3walls"

make_files() {
  mkdir "$USER_PATH/spong"
  cp "$USER_PATH/defaults/current-theme.txt" "$USER_PATH/spong/current-theme.txt"
  cp "$USER_PATH/defaults/current-themes.txt" "$USER_PATH/spong/current-themes.txt"
  touch "$USER_PATH/spong/walls.default"
}

populate_files() {
  echo "walls.default" > "$USER_PATH/spong/current-theme.txt"
  echo "walls.default" > "$USER_PATH/spong/current-themes.txt"
  ln -s "$USER_PATH/defaults/1.jpg" "$USER_PATH/spong/pic_01"
  ln -s "$USER_PATH/defaults/2.jpg" "$USER_PATH/spong/pic_02"
  ln -s "$USER_PATH/defaults/3.jpg" "$USER_PATH/spong/pic_03"
  ln -s "$USER_PATH/defaults/4.jpg" "$USER_PATH/spong/pic_04"
  ln -s "$USER_PATH/defaults/5.jpg" "$USER_PATH/spong/pic_05"
  ln -s "$USER_PATH/defaults/6.jpg" "$USER_PATH/spong/pic_06"
  ln -s "$USER_PATH/defaults/7.jpg" "$USER_PATH/spong/pic_07"
}

make_files
populate_files

# Update ~/.config/i3/config:85 with:

# # Do a background alias so we can have a random background on each workspace.
# # set $dofeh exec --no-startup-id feh --bg-scale 
#
# # switch to workspace
# # bindsym $mod+1 workspace $ws1; $dofeh ~/.config/i3/walls/pic_01
# # bindsym $mod+2 workspace $ws2; $dofeh ~/.config/i3/walls/pic_02
# # bindsym $mod+3 workspace $ws3; $dofeh ~/.config/i3/walls/pic_03
# # bindsym $mod+4 workspace $ws4; $dofeh ~/.config/i3/walls/pic_04
# # bindsym $mod+5 workspace $ws5; $dofeh ~/.config/i3/walls/pic_05
# # bindsym $mod+6 workspace $ws6; $dofeh ~/.config/i3/walls/pic_06
# # bindsym $mod+7 workspace $ws7; $dofeh ~/.config/i3/walls/pic_07
# # bindsym $mod+8 workspace $ws8; $dofeh --randomize ~/wallpapers/
# # bindsym $mod+9 workspace $ws9; $dofeh --randomize ~/wallpapers/
# # bindsym $mod+10 workspace $ws10; $dofeh --randomize ~/wallpapers/

# sudo ln -s ~/code/i3walls/i3walls /usr/local/bin/i3walls
