#!/bin/bash

INSTALL_PATH="/home/$USER/.config/i3"
SCRIPT_PATH="$(cd -- "$SCRIPT_PATH" && pwd)"
if [[ -z "$SCRIPT_PATH" ]] ; then
  exit 1  # fail
fi

make_files() {
  if [[ ! -d "$INSTALL_PATH/i3walls" ]]; then
    mkdir "$INSTALL_PATH/i3walls"
    cp "$SCRIPT_PATH/defaults/current-theme.txt" "$INSTALL_PATH/i3walls/current-theme.txt"
    cp "$SCRIPT_PATH/defaults/current-themes.txt" "$INSTALL_PATH/i3walls/current-themes.txt"
    touch "$INSTALL_PATH/i3walls/walls.default"
  fi

  if [[ ! -f /usr/local/bin/i3walls ]]; then
    sudo ln -s "$SCRIPT_PATH/i3walls" /usr/local/bin/i3walls
  fi
}

populate_files() {
  for i in {1..7}; do
    ln -s "$SCRIPT_PATH/defaults/$i.jpg" "$INSTALL_PATH/i3walls/pic_$i"
    echo "$SCRIPT_PATH/defaults/$i.jpg" >> "$INSTALL_PATH/i3walls/walls.default"
  done
}

make_files
populate_files

# Update ~/.config/i3/config:85 with:

# # Do a background alias so we can have a random background on each workspace.
# # set $dofeh exec --no-startup-id feh --bg-scale 
#
# # switch to workspace
# # bindsym $mod+1 workspace $ws1; $dofeh ~/.config/i3/walls/pic_1
# # bindsym $mod+2 workspace $ws2; $dofeh ~/.config/i3/walls/pic_2
# # bindsym $mod+3 workspace $ws3; $dofeh ~/.config/i3/walls/pic_3
# # bindsym $mod+4 workspace $ws4; $dofeh ~/.config/i3/walls/pic_4
# # bindsym $mod+5 workspace $ws5; $dofeh ~/.config/i3/walls/pic_5
# # bindsym $mod+6 workspace $ws6; $dofeh ~/.config/i3/walls/pic_6
# # bindsym $mod+7 workspace $ws7; $dofeh ~/.config/i3/walls/pic_7
# # bindsym $mod+8 workspace $ws8; $dofeh --randomize ~/wallpapers/
# # bindsym $mod+9 workspace $ws9; $dofeh --randomize ~/wallpapers/
# # bindsym $mod+10 workspace $ws10; $dofeh --randomize ~/wallpapers/
