#!/bin/bash

INSTALL_PATH="/home/$USER/.config/i3"
SCRIPT_PATH="$(cd -- "$SCRIPT_PATH" && pwd)"
if [[ -z "$SCRIPT_PATH" ]] ; then
  exit 1  # fail
fi

make_files() {
  if [[ ! -d "$INSTALL_PATH/i3walls" ]]; then
    mkdir "$INSTALL_PATH/i3walls"
    cp "$SCRIPT_PATH/defaults/current-theme.txt" "$INSTALL_PATH/i3walls/current-theme.txt"
    cp "$SCRIPT_PATH/defaults/current-themes.txt" "$INSTALL_PATH/i3walls/current-themes.txt"
    touch "$INSTALL_PATH/i3walls/walls.default"
  fi

  if [[ ! -f /usr/local/bin/i3walls ]]; then
    sudo ln -s "$SCRIPT_PATH/i3walls" /usr/local/bin/i3walls
  fi
}

populate_files() {
  for i in {1..10}; do
    ln -s "$SCRIPT_PATH/defaults/$i.jpg" "$INSTALL_PATH/i3walls/pic_$i"
    echo "$SCRIPT_PATH/defaults/$i.jpg" >> "$INSTALL_PATH/i3walls/walls.default"
  done
}

update_config() {
  # Backup the original i3 config
  cp "$INSTALL_PATH/config" "$INSTALL_PATH/config.bk"

  # Add the 'dofeh' line
  sed -i 's/set $ws10 "10"/set $ws10 "10"\n\n#i3walls\nset $dofeh exec --no-startup-id feh --bg-scale/' "$INSTALL_PATH/config"

  # Add the symlinks
  for i in {1..10}; do
    BIND_ORIG="bindsym \$mod+$i workspace \$ws$i"
    sed -i "s/$BIND_ORIG/$BIND_ORIG; \$dofeh ~\/.config\/i3\/i3walls\/pic_$i/" "$INSTALL_PATH/config"
  done

  # Modify the last symlink manually because workspace '10' is got to with mod+0.
    sed -i 's/bindsym $mod+0 workspace $ws10/bindsym $mod+0 workspace $ws10; $dofeh ~\/.config\/i3\/i3walls\/pic_10/' "$INSTALL_PATH/config"
}

make_files
populate_files
update_config

